/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.Penjoki;
import entity.Pemesanan;

import control.PenjokiControl;
import control.PemesananControl;

import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class ViewAdmin extends javax.swing.JFrame {
    private PenjokiControl pc;
    private PemesananControl peC;
    private int selectedId = 0;
    private String game;
    
    /**
     * Creates new form ViewAdmin
     */
    public ViewAdmin() {
        initComponents();
        pc = new PenjokiControl();
        peC = new PemesananControl();
        setComponent(false);
        clearDropdown();
        setTitle("Admin Page");
        showPemesananAdminPendingOngoing();
    }
    
    public void setDataDropdown(){
        dropdownStatus.addItem("On-going");
        dropdownStatus.addItem("Completed");
    }
    
    public void clearDropdown(){
        dropdownPenjoki.removeAllItems();
        dropdownPenjoki.addItem(new Penjoki(0, "< Pilih Data Pada Table >", "", 0));
        dropdownStatus.removeAllItems();
        dropdownStatus.addItem("< Pilih Data Pada Table >");
    }
    
    public void setComponent(boolean val){
        saveBtn.setEnabled(val);
        dropdownPenjoki.setEnabled(val);
        dropdownStatus.setEnabled(val);
    }
    
    public void showPenjokiToDropdown(String game){
        List<Penjoki> listPenjoki = pc.getPenjokiSpecific(game);
        
        for (Penjoki penjoki : listPenjoki) 
            dropdownPenjoki.addItem(penjoki); 
    }
    
    public void showPemesananAdmin(){
       tabelPemesanan.setModel(peC.getTablePemesananAdmin(inputSearch.getText()));
    }
    
    public void showPemesananAdminPendingOngoing(){
        tabelPemesanan.setModel(peC.getTablePemesananAdminPendingOngoing());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        penjokiBtn = new javax.swing.JButton();
        labelPenjoki = new javax.swing.JLabel();
        dropdownPenjoki = new javax.swing.JComboBox<>();
        labelStatus = new javax.swing.JLabel();
        dropdownStatus = new javax.swing.JComboBox<>();
        inputSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        contentHeader = new javax.swing.JPanel();
        labelAdmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        penjokiBtn.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        penjokiBtn.setText("Penjoki");
        penjokiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjokiBtnActionPerformed(evt);
            }
        });

        labelPenjoki.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelPenjoki.setForeground(new java.awt.Color(51, 51, 51));
        labelPenjoki.setText("Penjoki");

        dropdownPenjoki.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        labelStatus.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(51, 51, 51));
        labelStatus.setText("Status");

        dropdownStatus.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        dropdownStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Pilih Data Pada Table >" }));
        dropdownStatus.setToolTipText("");

        inputSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokiMLIcon/search_15pxneo.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 153, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setPreferredSize(new java.awt.Dimension(90, 31));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStatus)
                            .addComponent(labelPenjoki)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(penjokiBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdownPenjoki, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropdownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutBtn)
                        .addComponent(penjokiBtn)))
                .addGap(18, 18, 18)
                .addComponent(labelPenjoki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropdownPenjoki, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelStatus)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        contentHeader.setBackground(new java.awt.Color(0, 153, 255));

        labelAdmin.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        labelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        labelAdmin.setText("Admin Page");

        javax.swing.GroupLayout contentHeaderLayout = new javax.swing.GroupLayout(contentHeader);
        contentHeader.setLayout(contentHeaderLayout);
        contentHeaderLayout.setHorizontalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAdmin)
                .addGap(424, 424, 424))
        );
        contentHeaderLayout.setVerticalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHeaderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelAdmin)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "username_game", "password_game", "nama_game", "awal_rank", "target_rank", "biaya", "status_pemesanan", "nama_penjoki", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPemesanan.setAutoscrolls(false);
        tabelPemesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelPemesanan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelPemesanan.getTableHeader().setReorderingAllowed(false);
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);
        if (tabelPemesanan.getColumnModel().getColumnCount() > 0) {
            tabelPemesanan.getColumnModel().getColumn(0).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(1).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(2).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(3).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(4).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(5).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(6).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(7).setResizable(false);
            tabelPemesanan.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(contentHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contentHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penjokiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjokiBtnActionPerformed
        // TODO add your handling code here:
        ViewPenjoki VP = new ViewPenjoki();
        this.dispose();
        VP.setVisible(true);
    }//GEN-LAST:event_penjokiBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        ViewLogin VL = new ViewLogin();
        this.dispose();
        VL.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        // TODO add your handling code here:
       int clickedRow = tabelPemesanan.getSelectedRow();
       TableModel tableModel = tabelPemesanan.getModel();
       
       selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 9).toString());
       int penjokiId = Integer.parseInt(tableModel.getValueAt(clickedRow, 11).toString());
       
       if(penjokiId == 0)
           dropdownPenjoki.setEnabled(true);
       else
           dropdownPenjoki.setEnabled(false);
       
       String status = tableModel.getValueAt(clickedRow, 7).toString();
       
       dropdownPenjoki.removeAllItems();
       game = tableModel.getValueAt(clickedRow, 3).toString();
       
       List<Penjoki> listPenjokiSpecific = pc.getPenjokiSpecific(game);
       
       showPenjokiToDropdown(game);
       
       if(listPenjokiSpecific.isEmpty()){
           dropdownPenjoki.setEnabled(false);
           dropdownStatus.setEnabled(false);
           dropdownPenjoki.removeAllItems();
           dropdownPenjoki.addItem(new Penjoki(0, "< Tambah Penjoki Terlebih Dahulu >", "", 0));
           dropdownStatus.removeAllItems();
           dropdownStatus.addItem("< Tambah Penjoki Terlebih Dahulu >");
           return;
       }
       
       if(!status.equals("Pending")){
           int id_penjoki = Integer.parseInt(tableModel.getValueAt(clickedRow, 11).toString());
           int indexPenjoki = 0;
           
           for (Penjoki p : listPenjokiSpecific) 
                if(p.getId() == id_penjoki)
                    indexPenjoki = listPenjokiSpecific.indexOf(p);
           
           dropdownPenjoki.setSelectedIndex(indexPenjoki);
       }
       
       if(status.equals("Pending")){
            dropdownPenjoki.setSelectedIndex(0);
            dropdownStatus.setSelectedIndex(0);
            dropdownPenjoki.setEnabled(true);
            dropdownStatus.setEnabled(true);
            dropdownStatus.removeAllItems();
            saveBtn.setEnabled(true);
            setDataDropdown();
       }
       else if(status.equals("On-going")){
           dropdownPenjoki.setEnabled(false);
           dropdownStatus.setEnabled(true);
           dropdownStatus.removeAllItems();
           saveBtn.setEnabled(true);
           setDataDropdown();
       }
       else if(status.equals("Completed")){
           dropdownPenjoki.setEnabled(false);
           dropdownStatus.setEnabled(false);
           dropdownStatus.removeAllItems();
           dropdownStatus.addItem("< Pemesanan Sudah Selesai >");
           saveBtn.setEnabled(false);
       }
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        inputSearch.setText("");
        showPemesananAdminPendingOngoing();
        dropdownPenjoki.removeAllItems();
        clearDropdown();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        List<Pemesanan> listPemesanan = peC.getPemesananAdmin("");
        
        Pemesanan p = null;
        
        for (int i = 0; i < listPemesanan.size(); i++) {
            if(listPemesanan.get(i).getId() == selectedId) {
                p = listPemesanan.get(i);
                break;
            }
        }
 
        if(p.getStatus_pemesanan().equals("Pending")){
            List<Penjoki> listPenjokiSpecific = pc.getPenjokiSpecific(game);
            Penjoki joki = listPenjokiSpecific.get(dropdownPenjoki.getSelectedIndex());
            p.setPenjoki(joki);
        }

        p.setStatus_pemesanan(dropdownStatus.getSelectedItem().toString());
        
        peC.updatePenjokiStatus(p);
        inputSearch.setText("");
        showPemesananAdminPendingOngoing();
        setComponent(false);
        clearDropdown();
        dropdownPenjoki.setSelectedIndex(0);
        dropdownStatus.setSelectedIndex(0);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        showPemesananAdmin();
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentHeader;
    private javax.swing.JComboBox<Penjoki> dropdownPenjoki;
    private javax.swing.JComboBox<String> dropdownStatus;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelPenjoki;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton penjokiBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable tabelPemesanan;
    // End of variables declaration//GEN-END:variables
}
