/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.User;
import control.UserControl;
import exception.UserAlreadyCreatedException;
import exception.EmptyInputException;
import exception.UsernameException;
import exception.ConfirmPassException;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ViewRegister extends javax.swing.JFrame {
    private UserControl uc;
    /**
     * Creates new form ViewRegister
     */
    public ViewRegister() {
        initComponents();
        setTitle("Register Page");
        uc = new UserControl();
    }
    
    public void clearText(){
        inputNamaRegister.setText("");
        inputPassword.setText("");
        inputUsername.setText("");
        inputPasswordConfirm.setText("");
        radioShowPass.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        contentHeader = new javax.swing.JPanel();
        labelRegister = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        labelNamaRegister = new javax.swing.JLabel();
        inputNamaRegister = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        radioShowPass = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        labelConfirmPass = new javax.swing.JLabel();
        inputPasswordConfirm = new javax.swing.JPasswordField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentHeader.setBackground(new java.awt.Color(0, 153, 255));
        contentHeader.setPreferredSize(new java.awt.Dimension(641, 189));

        labelRegister.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        labelRegister.setForeground(new java.awt.Color(255, 255, 255));
        labelRegister.setText("Register User");

        javax.swing.GroupLayout contentHeaderLayout = new javax.swing.GroupLayout(contentHeader);
        contentHeader.setLayout(contentHeaderLayout);
        contentHeaderLayout.setHorizontalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHeaderLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(labelRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentHeaderLayout.setVerticalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHeaderLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(labelRegister)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backBtn.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        labelNamaRegister.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelNamaRegister.setText("Nama");

        inputNamaRegister.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelUsername.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelUsername.setText("Username");

        inputUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelPass.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelPass.setText("Password");

        inputPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        radioShowPass.setText("Show Password");
        radioShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioShowPassActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 153, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        labelConfirmPass.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelConfirmPass.setText("Confirm Password");

        inputPasswordConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(labelNamaRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(87, 87, 87))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addComponent(radioShowPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputNamaRegister)
                            .addComponent(inputPasswordConfirm)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(63, 63, 63))
                            .addComponent(inputUsername)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(labelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65))
                            .addComponent(inputPassword)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelConfirmPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioShowPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ViewLogin VL = new ViewLogin();
        this.dispose();
        VL.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String username = inputUsername.getText();
        
        try{
            String pass = new String(inputPassword.getPassword()); 
            String passConf = new String(inputPasswordConfirm.getPassword());
            
            User newUser = new User(username, pass, inputNamaRegister.getText());
            if(!pass.equals(passConf)) throw new ConfirmPassException();
            
            uc.checkUsername(username);
            uc.insertUser(newUser);
            clearText();
            JOptionPane.showConfirmDialog(null, "Berhasil Register User " + username + " !", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        }catch(UserAlreadyCreatedException e){
            JOptionPane.showConfirmDialog(null, e.message(), "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        }catch(EmptyInputException e){
            JOptionPane.showConfirmDialog(null, e.message(), "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            clearText();
        }catch(UsernameException e){
            JOptionPane.showConfirmDialog(null, e.message(username), "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            clearText();
        }catch(ConfirmPassException e){
            JOptionPane.showConfirmDialog(null, e.message(), "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void radioShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioShowPassActionPerformed
        // TODO add your handling code here:
        if(radioShowPass.isSelected()) {
            inputPassword.setEchoChar((char) 0);
            inputPasswordConfirm.setEchoChar((char) 0);
        }
        else {
            inputPassword.setEchoChar('*');
            inputPasswordConfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_radioShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel contentHeader;
    private javax.swing.JTextField inputNamaRegister;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JPasswordField inputPasswordConfirm;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelConfirmPass;
    private javax.swing.JLabel labelNamaRegister;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JRadioButton radioShowPass;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
