/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.UserControl;
import entity.User;
import control.PemesananControl;
import entity.Pemesanan;

import exception.EmptyInputException;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ViewUser extends javax.swing.JFrame {
    private final String rankDota[] = {"Herald", "Guardian", "Crusader", "Archon", "Legend", "Ancient", "Divine", "Immortal"};
    private final int hargaDota[] = {10000, 20000, 30000, 40000, 50000, 100000, 200000};
    private final String rankML[] = {"Warrior", "Elite", "Master", "Grand Master", "Epic", "Legend", "Mythic", "Mythical Glory"};
    private final int hargaML[] = {5000, 10000, 15000, 25000, 50000, 150000, 200000};
        
    private UserControl uc;
    private PemesananControl pc;
    private User current = uc.getCurrentUser();
    /**
     * Creates new form ViewUser
     */
    public ViewUser() {
        initComponents();
        labelWelcome.setText("Welcome, " + current.getNama() + " !");
        uc = new UserControl();
        pc = new PemesananControl();
        biayaField.setEnabled(false);
        setDropdown(false);
        setTitle("User Page");
        showTablePemesanan();
    }
    
    public void showTablePemesanan(){
        tabelUserPemesanan.setModel(pc.getTablePemesananUser(current.getId(), inputSearch.getText()));
    }
    
    public void clearText(){
        inputUsernameGame.setText("");
        inputPassword.setText("");
        inputSearch.setText("");
        biayaField.setText("");
        gameGroup.clearSelection();
        removeTierAwal();
        removeTierTarget();
        dropdownAwal.addItem("< Pilih Game Terlebih Dahulu >");
        dropdownTarget.addItem("< Pilih Game Terlebih Dahulu >");
    }
    
    
    public int getIdxTargetDota(){
        String data = String.valueOf(dropdownTarget.getSelectedItem());

        for(int i = 0 ; i < rankDota.length ; i++)
            if(data.equals(rankDota[i])) 
                return i-1;
        
        return -1;
    }
    
    public int getIdxTargetML(){
        String data = String.valueOf(dropdownTarget.getSelectedItem());

        for(int i = 0 ; i < rankML.length ; i++)
            if(data.equals(rankML[i])) 
                return i-1;
        
        return -1;
    }
    
    public void setBiayaDota(){
        int biaya = 0;        
        
        for(int i = dropdownAwal.getSelectedIndex() ; i <= getIdxTargetDota() ; i++)
            biaya += hargaDota[i];
        
        biayaField.setText(String.valueOf(biaya));
    }
    
    public void setBiayaML(){
        int biaya = 0;

        for(int i = dropdownAwal.getSelectedIndex() ; i <= getIdxTargetML() ; i++)
            biaya += hargaML[i];
        
        biayaField.setText(String.valueOf(biaya));
    }
    
    public void setDropdown(boolean val){
        dropdownAwal.setEnabled(val);
        dropdownTarget.setEnabled(val);
    }
    
    public void removeTierAwal(){
        dropdownAwal.removeAllItems();
    }
    
    public void removeTierTarget(){
        dropdownTarget.removeAllItems();
    }
    
    public void setTierDota(){ 
        removeTierAwal();
            
        for (int i = 0; i < rankDota.length - 1 ; i++)
            dropdownAwal.addItem(rankDota[i]);
    }
    
    public void setTierAkhirDota(){
        removeTierTarget();
        
        int idx = dropdownAwal.getSelectedIndex() + 1;
        
        for(int i = idx ; i < rankDota.length ; i++)
            dropdownTarget.addItem(rankDota[i]);
    }
    
     public void setTierML(){
        removeTierAwal();
         
        for (int i = 0; i < rankML.length - 1 ; i++) 
            dropdownAwal.addItem(rankML[i]);
    }
     
    public void setTierAkhirML(){
        removeTierTarget();
        
        int idx = dropdownAwal.getSelectedIndex() + 1;
        
        for(int i = idx ; i < rankML.length; i++)
            dropdownTarget.addItem(rankML[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameGroup = new javax.swing.ButtonGroup();
        contentHeader = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTarget = new javax.swing.JLabel();
        dropdownTarget = new javax.swing.JComboBox<>();
        labelUserGame = new javax.swing.JLabel();
        dropdownAwal = new javax.swing.JComboBox<>();
        labelAwalRank = new javax.swing.JLabel();
        biayaField = new javax.swing.JTextField();
        iconDota = new javax.swing.JLabel();
        radioBtnDota = new javax.swing.JRadioButton();
        radioBtnML = new javax.swing.JRadioButton();
        iconML = new javax.swing.JLabel();
        labelPasswordGame = new javax.swing.JLabel();
        inputPassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUserPemesanan = new javax.swing.JTable();
        labelJoki = new javax.swing.JLabel();
        inputUsernameGame = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();
        buyBtn = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentHeader.setBackground(new java.awt.Color(0, 153, 255));

        labelWelcome.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("Welcome, [...] !");

        javax.swing.GroupLayout contentHeaderLayout = new javax.swing.GroupLayout(contentHeader);
        contentHeader.setLayout(contentHeaderLayout);
        contentHeaderLayout.setHorizontalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentHeaderLayout.setVerticalGroup(
            contentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentHeaderLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(labelWelcome)
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelTarget.setBackground(new java.awt.Color(51, 51, 51));
        labelTarget.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelTarget.setForeground(new java.awt.Color(51, 51, 51));
        labelTarget.setText("Target Rank");

        dropdownTarget.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        dropdownTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Pilih Game Terlebih Dahulu >" }));
        dropdownTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownTargetActionPerformed(evt);
            }
        });

        labelUserGame.setBackground(new java.awt.Color(51, 51, 51));
        labelUserGame.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelUserGame.setForeground(new java.awt.Color(51, 51, 51));
        labelUserGame.setText("Username Game");

        dropdownAwal.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        dropdownAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Pilih Game Terlebih Dahulu >" }));
        dropdownAwal.setToolTipText("");
        dropdownAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownAwalActionPerformed(evt);
            }
        });

        labelAwalRank.setBackground(new java.awt.Color(51, 51, 51));
        labelAwalRank.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelAwalRank.setForeground(new java.awt.Color(51, 51, 51));
        labelAwalRank.setText("Awal Rank");

        biayaField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        biayaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaFieldActionPerformed(evt);
            }
        });

        iconDota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokiMLIcon/Dota 2_65px.png"))); // NOI18N

        gameGroup.add(radioBtnDota);
        radioBtnDota.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        radioBtnDota.setForeground(new java.awt.Color(51, 51, 51));
        radioBtnDota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDotaActionPerformed(evt);
            }
        });

        gameGroup.add(radioBtnML);
        radioBtnML.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        radioBtnML.setForeground(new java.awt.Color(51, 51, 51));
        radioBtnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMLActionPerformed(evt);
            }
        });

        iconML.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        iconML.setForeground(new java.awt.Color(51, 51, 51));
        iconML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokiMLIcon/ml 100 1.png"))); // NOI18N

        labelPasswordGame.setBackground(new java.awt.Color(51, 51, 51));
        labelPasswordGame.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelPasswordGame.setForeground(new java.awt.Color(51, 51, 51));
        labelPasswordGame.setText("Password Game");

        inputPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tabelUserPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "username_game", "nama_game", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelUserPemesanan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelUserPemesanan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelUserPemesanan);
        if (tabelUserPemesanan.getColumnModel().getColumnCount() > 0) {
            tabelUserPemesanan.getColumnModel().getColumn(0).setResizable(false);
            tabelUserPemesanan.getColumnModel().getColumn(1).setResizable(false);
            tabelUserPemesanan.getColumnModel().getColumn(2).setResizable(false);
        }

        labelJoki.setBackground(new java.awt.Color(51, 51, 51));
        labelJoki.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        labelJoki.setForeground(new java.awt.Color(51, 51, 51));
        labelJoki.setText("Biaya Joki");

        inputUsernameGame.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        logoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        buyBtn.setBackground(new java.awt.Color(0, 153, 255));
        buyBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buyBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn.setText("Bayar");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        inputSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokiMLIcon/search_15pxneo.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(radioBtnDota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconDota)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnML)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconML))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelUserGame)
                                    .addComponent(labelTarget)
                                    .addComponent(labelAwalRank)
                                    .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(labelPasswordGame)
                                    .addComponent(dropdownAwal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dropdownTarget, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputUsernameGame))))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelJoki))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputSearch, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biayaField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelUserGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputUsernameGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelJoki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biayaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(labelPasswordGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(iconML))
                            .addComponent(radioBtnML, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iconDota)
                                    .addComponent(radioBtnDota))))
                        .addGap(26, 26, 26)
                        .addComponent(labelAwalRank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdownAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(labelTarget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdownTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(contentHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdownTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownTargetActionPerformed
        // TODO add your handling code here:
        if(radioBtnDota.isSelected() && dropdownTarget.isPopupVisible()) 
            setBiayaDota();  
        else if(radioBtnML.isSelected() && dropdownTarget.isPopupVisible()) 
            setBiayaML();
    }//GEN-LAST:event_dropdownTargetActionPerformed

    private void dropdownAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownAwalActionPerformed
        // TODO add your handling code here:
        if(radioBtnDota.isSelected() && dropdownAwal.isPopupVisible()) {
            setTierAkhirDota();
            setBiayaDota();
        }
        else if(radioBtnML.isSelected() && dropdownAwal.isPopupVisible()) {
            setTierAkhirML();
            setBiayaML();
        }

    }//GEN-LAST:event_dropdownAwalActionPerformed

    private void radioBtnDotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDotaActionPerformed
        // TODO add your handling code here:
        setTierDota();
        setTierAkhirDota();
        setBiayaDota();
        setDropdown(true);
    }//GEN-LAST:event_radioBtnDotaActionPerformed

    private void radioBtnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMLActionPerformed
        // TODO add your handling code here:
        setTierML();
        setTierAkhirML();
        setBiayaML();
        setDropdown(true);
    }//GEN-LAST:event_radioBtnMLActionPerformed

    private void biayaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaFieldActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        ViewLogin VL = new ViewLogin();
        this.dispose();
        VL.setVisible(true);
        uc.setNull();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        // TODO add your handling code here:
        try{
            String awal, akhir, pick = "";
            awal = String.valueOf(dropdownAwal.getSelectedItem());
            akhir = String.valueOf(dropdownTarget.getSelectedItem());
            
            if(radioBtnDota.isSelected()) pick = "Dota 2";
            else if(radioBtnML.isSelected()) pick = "Mobile Legends";
            
            Pemesanan p = new Pemesanan(inputUsernameGame.getText(),inputPassword.getText(), pick, awal, akhir, 
                    Integer.parseInt(biayaField.getText()), "Pending", 
                    current.getId(), current.getUsername(), current.getPassword(), current.getNama());
            
            pc.insertPemesanan(p);
            clearText();
            setDropdown(false);
            showTablePemesanan();
        }catch(EmptyInputException e){
            JOptionPane.showConfirmDialog(null, e.message(), "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        }catch(NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Input tidak boleh kosong!", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_buyBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        showTablePemesanan();
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaField;
    private javax.swing.JButton buyBtn;
    private javax.swing.JPanel contentHeader;
    private javax.swing.JComboBox<String> dropdownAwal;
    private javax.swing.JComboBox<String> dropdownTarget;
    private javax.swing.ButtonGroup gameGroup;
    private javax.swing.JLabel iconDota;
    private javax.swing.JLabel iconML;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputUsernameGame;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAwalRank;
    private javax.swing.JLabel labelJoki;
    private javax.swing.JLabel labelPasswordGame;
    private javax.swing.JLabel labelTarget;
    private javax.swing.JLabel labelUserGame;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JRadioButton radioBtnDota;
    private javax.swing.JRadioButton radioBtnML;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable tabelUserPemesanan;
    // End of variables declaration//GEN-END:variables
}
